# Generated by Django 4.2.4 on 2023-08-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_texted_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='last_texted_at',
            ),
        ),
    ]
