version: '3.9'
name: 'referral_system_dev'

services:
  postgres:
    image: postgres:14
    volumes:
      - postgres_value:/var/lib/postgresql/data
      - ../../pg-initdb:/docker-entrypoint-initdb.d
    env_file:
      - ./.env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --username ${POSTGRES_USER} --dbname ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "${POSTGRES_PORT}:5432"
volumes:
  postgres_value:
